
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: shadyemad/gitops-app:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: gitops-app
spec:
  type: LoadBalancer 
  selector:
    app: gitops-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000 #container port
    nodePort: 30080
